### ISSUE TITLE
Cannot start jingo with the provided YAML file?

### ISSUE THREAD

**Issue by filipbarak** [claudioc/jingo#228]
C:\Users\Filip Barak\AppData\Roaming\npm\node_modules\jingo\node_modules\js-yaml\lib\js-yaml\loader.js:171
  throw generateError(state, message);
  ^
YAMLException: end of the stream or a document separator is expected at line 1, column 4:
    ��-
       ^
    at generateError (C:\Users\Filip Barak\AppData\Roaming\npm\node_modules\jingo\node_modules\js-yaml\lib\js-yaml\loade
r.js:165:10)
    at throwError (C:\Users\Filip Barak\AppData\Roaming\npm\node_modules\jingo\node_modules\js-yaml\lib\js-yaml\loader.j
s:171:9)
    at readDocument (C:\Users\Filip Barak\AppData\Roaming\npm\node_modules\jingo\node_modules\js-yaml\lib\js-yaml\loader
.js:1512:5)
    at loadDocuments (C:\Users\Filip Barak\AppData\Roaming\npm\node_modules\jingo\node_modules\js-yaml\lib\js-yaml\loade
r.js:1548:5)
    at Object.load (C:\Users\Filip Barak\AppData\Roaming\npm\node_modules\jingo\node_modules\js-yaml\lib\js-yaml\loader.
js:1569:19)
    at Object.load (C:\Users\Filip Barak\AppData\Roaming\npm\node_modules\jingo\lib\config.js:12:23)
    at Object.<anonymous> (C:\Users\Filip Barak\AppData\Roaming\npm\node_modules\jingo\jingo:43:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
PS C:\Users\Filip Barak\Documents> ls

    Directory: C:\Users\Filip Barak\Documents

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        10/7/2017   5:19 PM                code
d-----        10/7/2017   3:27 PM                Lightshot
d-----        9/16/2017   3:10 PM                nodejs
d-----        9/16/2017  12:15 AM                Programs
d-----        9/16/2017   9:04 AM                Scripts
-a----        10/8/2017   9:52 AM           3092 config.yaml

I am using the jingo -s > config.yaml generated file and just edited the local: true. Haven't touched anything else.

Help?

**Comment by claudioc** [comment]
Hey Filip,

it really looks like a syntax error of some type in the yaml config file, maybe due to the Windows line breaks?

I also do not support Jingo in Windows, so it might be working or not, sorry :)

(try searching the issue for some other people having problem with Windows in the past)
