### ISSUE TITLE
Issue with favicon

### ISSUE THREAD

**Issue by alehandrof** [claudioc/jingo#64]
When I run `jingo -c config.yaml` I get this error:

```
fs.js:696
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/home/alex/Desktop/ninth-hour/public/favicon.ico'
    at Object.fs.statSync (fs.js:696:18)
    at favicon (/home/alex/.node/lib/node_modules/jingo/node_modules/serve-favicon/index.js:55:15)
    at Object.module.exports.initialize (/home/alex/.node/lib/node_modules/jingo/lib/app.js:107:11)
    at start (/home/alex/.node/lib/node_modules/jingo/jingo:82:34)
    at /home/alex/.node/lib/node_modules/jingo/jingo:77:3
    at Object.<anonymous> (/home/alex/.node/lib/node_modules/jingo/lib/gitmech.js:153:7)
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
```

I'm on Ubuntu 14.04, and I've installed jingo globally using the [sudoless npm install](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md).

**Comment by claudioc** [comment]
Hi Alex,

sorry to hear that, but this is the first time I receive this bug report, very strange.

Can you tell me if the file `/home/alex/Desktop/ninth-hour/public/favicon.ico` exists and is readable?

Thank you!

**Comment by alehandrof** [comment]
Why would it exist? :)

I've done this inside my test repo (`/home/alex/Desktop/ninth-hour`):

```
npm install -g jingo
jingo -s > config.yaml
```

I then edited config.yaml to include my repo's path in line 5.

And then this:

```
alex@tosh:~/Desktop/ninth-hour$ jingo -c config.yaml 

fs.js:696
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/home/alex/Desktop/ninth-hour/public/favicon.ico'
    at Object.fs.statSync (fs.js:696:18)
    at favicon (/home/alex/.node/lib/node_modules/jingo/node_modules/serve-favicon/index.js:55:15)
    at Object.module.exports.initialize (/home/alex/.node/lib/node_modules/jingo/lib/app.js:107:11)
    at start (/home/alex/.node/lib/node_modules/jingo/jingo:82:34)
    at /home/alex/.node/lib/node_modules/jingo/jingo:77:3
    at Object.<anonymous> (/home/alex/.node/lib/node_modules/jingo/lib/gitmech.js:153:7)
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

I must have skipped a step or something.

**Comment by claudioc** [comment]
OK, thanks. I think you might have found a bug indeed. I am looking into it right now.

**Comment by claudioc** [comment]
Thank you, fixed :)

**Comment by alehandrof** [comment]
Wicked, thank you :)
